// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository.Db;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(HelpDbContext))]
    [Migration("20251008061344_notification")]
    partial class notification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Audit.AuditLogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionType")
                        .HasColumnType("integer");

                    b.Property<int>("ChangedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityName")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog", "log");
                });

            modelBuilder.Entity("Models.Entities.Audit.RefreshTokenModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FkLoginId")
                        .HasColumnType("integer");

                    b.Property<int>("FkUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<string>("UserIp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens", "log");
                });

            modelBuilder.Entity("Models.Entities.Audit.UserLoginModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Browser")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("FkUserId")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineUser")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.ToTable("UserLogins", "log");
                });

            modelBuilder.Entity("Models.Entities.Issue.LeadCustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<string>("CustomerFirstName")
                        .HasColumnType("text");

                    b.Property<string>("CustomerLastName")
                        .HasColumnType("text");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FKCompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("ProjectAddress")
                        .HasColumnType("text");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKCompanyId");

                    b.ToTable("LeadCustomer", "issue");
                });

            modelBuilder.Entity("Models.Entities.Issue.ResolutionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("FKCompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKCompanyId");

                    b.ToTable("Resolution", "issue");
                });

            modelBuilder.Entity("Models.Entities.Issue.RootCauseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("FKCompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKCompanyId");

                    b.ToTable("RootCause", "issue");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketAttachmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FKTicketId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKTicketId");

                    b.ToTable("TicketAttachment", "issue");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketCommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("MentionUserIds")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int>("TicketId")
                        .HasColumnType("integer");

                    b.Property<int?>("TicketModelId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("TicketModelId");

                    b.ToTable("TicketComment", "issue");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketDepartmentMapModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FKDepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("FKTicketId")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKDepartmentId");

                    b.HasIndex("FKTicketId");

                    b.ToTable("TicketDepartmentMap", "issue");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketLeadCustomerMapModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FKLeadCustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("FKTicketId")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKLeadCustomerId");

                    b.HasIndex("FKTicketId");

                    b.ToTable("TicketLeadCustomerMap", "issue");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketLinkModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("ExternalKey")
                        .HasColumnType("text");

                    b.Property<int>("FKTicketId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKTicketId");

                    b.ToTable("TicketLink", "issue");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EstimatedTime")
                        .HasColumnType("text");

                    b.Property<int>("FKCompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("FKTicketTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("ResolutionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RootCauseId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("TicketCategory")
                        .HasColumnType("integer");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKCompanyId");

                    b.HasIndex("FKTicketTypeId");

                    b.ToTable("Ticket", "issue");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FKAssignedUserId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("FkDepartmentIds")
                        .HasColumnType("integer[]");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKAssignedUserId");

                    b.ToTable("TicketType", "issue");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketWatchListModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FKTicketId")
                        .HasColumnType("integer");

                    b.Property<int>("FKUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKTicketId");

                    b.HasIndex("FKUserId");

                    b.ToTable("TicketWatchList", "issue");
                });

            modelBuilder.Entity("Models.Entities.Notification.NotificationTemplateModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyTemplate")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int?>("EmailConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<int>("FkCompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<string>("SubjectTemplate")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.PrimitiveCollection<string[]>("Variables")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("NotificationTemplate", "notification");
                });

            modelBuilder.Entity("Models.Entities.Org.CompanyDefineDataSourceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int>("DataSourceType")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FkCompanyId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSync")
                        .HasColumnType("boolean");

                    b.Property<string>("JsonData")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FkCompanyId");

                    b.ToTable("CompanyDefineDataSources", "Org");
                });

            modelBuilder.Entity("Models.Entities.Org.CompanyModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessKey")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LastTicketNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PrefixTicket")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<string>("SecretKey")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.ToTable("Companies", "Org");
                });

            modelBuilder.Entity("Models.Entities.Org.CustomFieldModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int>("FkTicketTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FkTicketTypeId");

                    b.ToTable("CustomFields", "Org");
                });

            modelBuilder.Entity("Models.Entities.Org.DepartmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("FKCompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("FKManagerId")
                        .HasColumnType("integer");

                    b.Property<int?>("IntegrationsPrimaryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKCompanyId");

                    b.HasIndex("FKManagerId");

                    b.ToTable("Department", "Org");
                });

            modelBuilder.Entity("Models.Entities.Org.SLAConfigurationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FKCompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FKCompanyId");

                    b.ToTable("SLAConfiguration", "Org");
                });

            modelBuilder.Entity("Models.Entities.Org.TicketCustomFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FkTicketId")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int>("TicketTypeCustomFieldId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FkTicketId");

                    b.HasIndex("TicketTypeCustomFieldId");

                    b.ToTable("TicketCustomFields", "Org");
                });

            modelBuilder.Entity("Models.Entities.Setup.EmailConfigurationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessKey")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("BCC")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("CcList")
                        .HasColumnType("text[]");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("Event")
                        .HasColumnType("integer");

                    b.Property<string>("Host")
                        .HasColumnType("text");

                    b.Property<int>("IMAPPort")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<string>("ReplyTo")
                        .HasColumnType("text");

                    b.Property<int>("SMTPPort")
                        .HasColumnType("integer");

                    b.Property<string>("SecretKey")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailConfiguration", "setup");
                });

            modelBuilder.Entity("Models.Entities.Setup.NotificationScheduleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("FKEmailConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int>("FKNotificationConfigId")
                        .HasColumnType("integer");

                    b.Property<int?>("FKTicketId")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("NotificationType")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<string>("Recipient")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKEmailConfigurationId");

                    b.HasIndex("FKTicketId");

                    b.ToTable("NotificationSchedule", "setup");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.AssociateActionRouteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int?>("FkMenuActionMapId")
                        .HasColumnType("integer");

                    b.Property<string>("HttpVerb")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FkMenuActionMapId");

                    b.ToTable("AssociateActionRoutes");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuActionDepartmentMappingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FKMenuActionMapId")
                        .HasColumnType("integer");

                    b.Property<int>("FkDepartmentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKMenuActionMapId");

                    b.HasIndex("FkDepartmentId");

                    b.ToTable("MenuActionDepartmentMapping", "UserMgmt");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuActionMapModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiUrl")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FKMenuActionId")
                        .HasColumnType("integer");

                    b.Property<int>("FKMenuId")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<string>("RoutePath")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKMenuActionId");

                    b.HasIndex("FKMenuId");

                    b.ToTable("MenuActionMap", "UserMgmt");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuActionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("HttpVerb")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.ToTable("MenuAction", "UserMgmt");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuActionRoleMappingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FKMenuActionMapId")
                        .HasColumnType("integer");

                    b.Property<int>("FKRoleId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("boolean");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.HasIndex("FKMenuActionMapId");

                    b.HasIndex("FKRoleId");

                    b.ToTable("MenuActionRoleMapping", "UserMgmt");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("IconClass")
                        .HasColumnType("text");

                    b.Property<string>("IconViewBox")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<string>("Route")
                        .HasColumnType("text");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Menu", "UserMgmt");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.RoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("HomeUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.HasKey("Id");

                    b.ToTable("Role", "UserMgmt");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int?>("FkCompanyId")
                        .HasColumnType("integer");

                    b.Property<int?>("FkDepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<int?>("IntegrationsPrimaryId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsReportingManager")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastPasswordChange")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FkDepartmentId");

                    b.ToTable("Users", "UserMgmt");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.UserRoleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(102);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(103);

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(106);

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(107);

                    b.Property<int>("FKRoleId")
                        .HasColumnType("integer");

                    b.Property<int>("FKUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RStatus")
                        .HasColumnType("integer")
                        .HasColumnOrder(101);

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer")
                        .HasColumnOrder(104);

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnOrder(105);

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", "UserMgmt");
                });

            modelBuilder.Entity("Models.Entities.Audit.AuditLogModel", b =>
                {
                    b.HasOne("Models.Entities.UserManagement.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Entities.Issue.LeadCustomerModel", b =>
                {
                    b.HasOne("Models.Entities.Org.CompanyModel", "Company")
                        .WithMany()
                        .HasForeignKey("FKCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Models.Entities.Issue.ResolutionModel", b =>
                {
                    b.HasOne("Models.Entities.Org.CompanyModel", "Company")
                        .WithMany()
                        .HasForeignKey("FKCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Models.Entities.Issue.RootCauseModel", b =>
                {
                    b.HasOne("Models.Entities.Org.CompanyModel", "Company")
                        .WithMany()
                        .HasForeignKey("FKCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketAttachmentModel", b =>
                {
                    b.HasOne("Models.Entities.Issue.TicketModel", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("FKTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketCommentModel", b =>
                {
                    b.HasOne("Models.Entities.Issue.TicketModel", null)
                        .WithMany("Comments")
                        .HasForeignKey("TicketModelId");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketDepartmentMapModel", b =>
                {
                    b.HasOne("Models.Entities.Org.DepartmentModel", "Department")
                        .WithMany()
                        .HasForeignKey("FKDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Issue.TicketModel", "Ticket")
                        .WithMany("DepartmentMaps")
                        .HasForeignKey("FKTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketLeadCustomerMapModel", b =>
                {
                    b.HasOne("Models.Entities.Issue.LeadCustomerModel", "Project")
                        .WithMany()
                        .HasForeignKey("FKLeadCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Issue.TicketModel", "Ticket")
                        .WithMany("LeadCustomerMaps")
                        .HasForeignKey("FKTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketLinkModel", b =>
                {
                    b.HasOne("Models.Entities.Issue.TicketModel", "Ticket")
                        .WithMany("Links")
                        .HasForeignKey("FKTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketModel", b =>
                {
                    b.HasOne("Models.Entities.Issue.TicketModel", "Ticket")
                        .WithMany()
                        .HasForeignKey("FKCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Issue.TicketTypeModel", "TicketType")
                        .WithMany()
                        .HasForeignKey("FKTicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketTypeModel", b =>
                {
                    b.HasOne("Models.Entities.UserManagement.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("FKAssignedUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketWatchListModel", b =>
                {
                    b.HasOne("Models.Entities.Issue.TicketModel", "Ticket")
                        .WithMany("WatchList")
                        .HasForeignKey("FKTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.UserManagement.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("FKUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Entities.Org.CompanyDefineDataSourceModel", b =>
                {
                    b.HasOne("Models.Entities.Org.CompanyModel", "Company")
                        .WithMany("CompanyDefineData")
                        .HasForeignKey("FkCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Models.Entities.Org.CustomFieldModel", b =>
                {
                    b.HasOne("Models.Entities.Issue.TicketTypeModel", "TicketType")
                        .WithMany()
                        .HasForeignKey("FkTicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketType");
                });

            modelBuilder.Entity("Models.Entities.Org.DepartmentModel", b =>
                {
                    b.HasOne("Models.Entities.Org.CompanyModel", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("FKCompanyId");

                    b.HasOne("Models.Entities.UserManagement.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("FKManagerId");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Entities.Org.SLAConfigurationModel", b =>
                {
                    b.HasOne("Models.Entities.Org.CompanyModel", "Company")
                        .WithMany()
                        .HasForeignKey("FKCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Models.Entities.Org.TicketCustomFieldValue", b =>
                {
                    b.HasOne("Models.Entities.Issue.TicketModel", "Ticket")
                        .WithMany()
                        .HasForeignKey("FkTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Org.CustomFieldModel", "CustomField")
                        .WithMany()
                        .HasForeignKey("TicketTypeCustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomField");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Models.Entities.Setup.NotificationScheduleModel", b =>
                {
                    b.HasOne("Models.Entities.Setup.EmailConfigurationModel", "EmailConfiguration")
                        .WithMany()
                        .HasForeignKey("FKEmailConfigurationId");

                    b.HasOne("Models.Entities.Issue.TicketModel", "Ticket")
                        .WithMany()
                        .HasForeignKey("FKTicketId");

                    b.Navigation("EmailConfiguration");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.AssociateActionRouteModel", b =>
                {
                    b.HasOne("Models.Entities.UserManagement.MenuActionMapModel", "MenuActionMap")
                        .WithMany()
                        .HasForeignKey("FkMenuActionMapId");

                    b.Navigation("MenuActionMap");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuActionDepartmentMappingModel", b =>
                {
                    b.HasOne("Models.Entities.UserManagement.MenuActionMapModel", "MenuActionMap")
                        .WithMany()
                        .HasForeignKey("FKMenuActionMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Org.DepartmentModel", "Department")
                        .WithMany()
                        .HasForeignKey("FkDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("MenuActionMap");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuActionMapModel", b =>
                {
                    b.HasOne("Models.Entities.UserManagement.MenuActionModel", "MenuAction")
                        .WithMany("MenuActionMaps")
                        .HasForeignKey("FKMenuActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.UserManagement.MenuModel", "Menu")
                        .WithMany("MenuActionMaps")
                        .HasForeignKey("FKMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("MenuAction");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuActionRoleMappingModel", b =>
                {
                    b.HasOne("Models.Entities.UserManagement.MenuActionMapModel", "MenuActionMap")
                        .WithMany("MenuActionRoleMappings")
                        .HasForeignKey("FKMenuActionMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.UserManagement.RoleModel", "Role")
                        .WithMany("MenuActionRoleMappings")
                        .HasForeignKey("FKRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuActionMap");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.UserModel", b =>
                {
                    b.HasOne("Models.Entities.Org.DepartmentModel", "Department")
                        .WithMany()
                        .HasForeignKey("FkDepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.UserRoleModel", b =>
                {
                    b.HasOne("Models.Entities.UserManagement.RoleModel", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("Models.Entities.UserManagement.UserModel", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Models.Entities.Issue.TicketModel", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("DepartmentMaps");

                    b.Navigation("LeadCustomerMaps");

                    b.Navigation("Links");

                    b.Navigation("WatchList");
                });

            modelBuilder.Entity("Models.Entities.Org.CompanyModel", b =>
                {
                    b.Navigation("CompanyDefineData");

                    b.Navigation("Departments");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuActionMapModel", b =>
                {
                    b.Navigation("MenuActionRoleMappings");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuActionModel", b =>
                {
                    b.Navigation("MenuActionMaps");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.MenuModel", b =>
                {
                    b.Navigation("MenuActionMaps");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.RoleModel", b =>
                {
                    b.Navigation("MenuActionRoleMappings");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Models.Entities.UserManagement.UserModel", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
