version: "3.9"

services:
  webapi.api:
    build:
      context: ../..
      dockerfile: help-desk-api/WebApi/Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection:  Host=postgres;Port=5432;Database=postgres;Username=saiful;Password=123654
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp
      POSTGRES_DB: erp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
